config/routes.rb
GeeFu::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  root :to => "pages#index"

  #get "/browse", :to => "experiments#index"
  get "/signed_up", :to => "pages#signed_up", :as => :signed_up
  get 'begin' => 'pages#index'

  authenticate :user do
    #resources :organisms
    #resources :genomes
    #resources :experiments
    #resources :features
    resources :tools
    resources :admin
  end

  resources :organisms
  resources :genomes
  resources :experiments
  resources :features

  scope "features" do
    get "/getgroup/:id", to: "features#getIdFromGroup"
  end

  scope "/features/search" do
    post "/id", to: "features#search_by_id", as: :feature_search_by_id
    post "/attribute", to: "features#search_by_attribute", as: :feature_search_by_attribute
    post "/summary", to: "features#summary", as: :feature_search_by_range
    get "/genome/typeahead", to: "features#genome_typeahead"
    get "/experiment/typeahead", to: "features#experiment_typeahead"
    post "/build", to: "features#display_all_by_build", as: :feature_display_all_by_build
  end

  scope "/tools" do
    post "/sequence", to: "tools#genomic_sequence", as: :tools_genomic_sequence
  end



  scope "/genomes" do
    get "/reference_list", to: "genomes#reference_list"
  end

  scope "/experiments" do
    get "/reference_list", to: "experiments#reference_list"
    get "/:id/:segment", to: "experiments#show"
  end

  scope "/features/dalliance" do
    get "/part/:exid/:part", to: "features#dalliance_part",:constraints => { :part => /.*/ }
    get "/:exid/:part", to: "features#dalliance_get",:constraints => { :part => /.*/ }
    get "/:exid/:part/:featutype/", to: "features#dalliance_get",:constraints => { :part => /.*/ }
  end

  scope "/genomes/dalliance/" do
    get "/:exid/:part/sequence", to: "features#dalliance_genome"
    get ":experiment/:sequence/entry_points", to: "features#dalliance_entry_points"
  end

  scope "/users" do
    get "/admin", to: "admin#index"
  end

  scope "/badges" do
    get "/badge/:badge", to: "Pages#getbadge"
    # get "/card/:email/:badge", to: "Pages#getcard"
  end

match "/badges/card/:email/:badge" => "Pages#getcard",
    :constraints => { :email => /.+@.+\..*/ }

  scope "/genomes/annoj" do
    get "/:id", to: "genomes#annoj"
  end

  match '/admin/:id', :to => 'admin#show', :as => :user

  mount SequenceServer::App, :at => "sequenceserver"

  scope "/sequenceserver" do
    get "/get_sequence", to: "experiments#findfromss"
  end

  # match "/webapollo" => redirect("http://geefu.oadb.tsl.ac.uk:8080/WebApollo/"), :as => :webapollo
  # match "/webapollo2" => redirect("http://geefu.oadb.tsl.ac.uk:8080/WebApollo2/"), :as => :webapollo2


require 'gollum/frontend/app'

  Precious::App.set(:gollum_path, Rails.root.join('wiki').to_s)
  Precious::App.set(:default_markup, :markdown) # set your favorite markup language
  Precious::App.set(:wiki_options, {:universal_toc => false})
  mount Precious::App, at: 'wiki'


# TODO review these for security
  resources :references
  match 'features/objects' => 'features#objects'
  match 'features/depth' => 'features#depth'
  match 'tools/genomic_sequence' => 'tools#genomic_sequence'
  match 'tools/export' => 'tools#export'
  match '/:controller(/:action(/:id))'
end

app/models/genome.rb
require 'bio'
require 'reference'

class Genome < ActiveRecord::Base
  include Concerns::Versioning

  belongs_to :organism
  has_many :references, :dependent => :destroy
  has_many :experiments

  validates :build_version, presence: true, uniqueness: {scope: :organism_id, message: "Build version must be unique to a genome"}
  validates_presence_of :fasta_file

  attr_accessor :fasta_file, :yaml_file
  attr_accessible :build_version, :fasta_file, :yaml_file, :meta, :organism_id

  has_paper_trail

  def to_s
    "#{organism.local_name} / #{build_version}"
  end

  def to_fasta
    references.map { |reference|
      Bio::Sequence::NA.new(reference.sequence.sequence).to_fasta(reference.name, 60)
    }.join("\n")
  end

  def html_meta
    self.meta ? self.meta.to_yaml.gsub!(/\n/, "<br/>").gsub!(/\s/, "&nbsp;").html_safe : ''
  end

  def meta_as_data_structure
    self.meta ? JSON::parse(self.meta) : nil
  end
end

app/controllers/genomes_controller.rb
#Implements the REST requests for the Genomes table/model
#access via url
class GenomesController < ApplicationController

  before_filter :require_organism
  
  #returns the genome information on an AnnoJ genome request
  # only for use by AnnoJ
  def annoj  #a method for annoj
    genome = Genome.find(params[:id])
    @response = {}
    @response["success"] = true
    @response["data"] = JSON::parse( "#{genome.meta}" ) #{}
    @response["data"]["genome"]["assemblies"] = []
    genome.references.each do |r|
      @response["data"]["genome"]["assemblies"] << {:id => r.name, :size => r.length}
    end
    render :json => @response, :layout => false #render :json => @genome doesnt work because annoj wont accept extra keys made by json-ing of ruby object..
  end

  #returns the list of genomes and associated meta-data in the database
  # use /genomes.format
  # where format = xml or js
  def index #regular web request method
    @genomes = Genome.all
    @genomes.each do |gen|
      gen.meta ? gen.meta = JSON::parse("#{gen.meta}") : nil
    end
    respond @genomes
  end

  #returns metadata for a selected genome 
  # use /genome/id.format
  # where format = xml or json
  def show
    if Genome.exists?(params[:id])
     @genome = Genome.find(params[:id])
     @genome.meta = @genome.meta_as_data_structure     
     respond @genome
    else
      respond :false
    end
  end
  
  def edit
    @genome = Genome.find(params[:id])
  end
  
  def new
    @organisms = Organism.all
    @genome = Genome.new
    respond @genome
  end
  
  #returns a list of references for the genome for the ajax autofill box
  def reference_list
    genome = Genome.find(params[:id])
    respond genome.references.collect {|x| x.name }
  end

  def create
    require 'bio'
    @genome = Genome.new(params[:genome])
    
    #fastasavename = rand(1000000).to_s
    #FileUtils.mv @genome.fasta_file.path, "#{RAILS_ROOT}/tmp/#{fastasavename}" if @genome.fasta_file
    #fasta = File.new("#{RAILS_ROOT}/tmp/#{savename}", "r")
   
    #fasta = params[:genome][:fasta_file]
    #yaml = params[:genome][:yaml]
    
    #format the meta data string from a provided yaml file
    if @genome.yaml_file
      @genome.meta = YAML::load_file(@genome.yaml_file.path).to_json 
    end
    
    #add the reference objects and sequence objects for this file...
    if @genome.fasta_file

      Bio::FastaFormat.open(@genome.fasta_file.path).each do |entry|
          seq = entry.to_seq
          reference = Reference.new(:name => entry.entry_id, :length => entry.length)
          sequence = Sequence.new(:sequence => "#{seq.seq}")
          reference.sequence = sequence        
          @genome.references << reference
        end
    end
    
    respond_to do |format|
      if @genome.save
        flash[:notice] = "Genome was successfully created."
        format.html { redirect_to(@genome) }
     else
        format.html { render :action => "new" }
    end
    end
  end
  
  def destroy
    @genome = Genome.find(params[:id])
    @genome.destroy
    respond_to do |format|
      format.html { redirect_to(genomes_url) }
    end
  end
  
  def respond(response)
    respond_to do |format|
      format.html
      format.json { render :json => response, :layout => false }
      format.xml  { render :xml => response, :layout => false }
    end
  end

  def require_organism
    redirect_to root_path unless has_organisms?
  end

end

app/helpers/genomes_helper.rb
module GenomesHelper
end

app/views/genomes/_form.html.erb
<%= simple_form_for @genome, html: { class: "form-horizontal" } do |f| %>
  <%= f.error_notification %>
  <%= f.input :organism_id, collection: Organism.all, prompt: "Choose an organism...", required: true %>
  <%= f.input :build_version, as: :string, required: true %>
  <%= f.input :fasta_file, as: :file, required: true%>
    <%= f.input :meta, as: :string, required: false %>
  <!--<%= f.input :yaml_file, as: :file, hint: "(required for AnnoJ browsing only)"%>-->
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                genomes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/genomes/edit.html.erb
<%- model_class = Genome -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= simple_form_for @genome, html: { class: "form-horizontal" } do |f| %>
    <%= f.error_notification %>
    <%= f.input :organism_id, collection: Organism.all, prompt: "Choose an organism...", required: true %>
    <%= f.input :build_version, as: :string%>
    <!--<%= f.input :fasta_file, as: :file%>-->
    <%= f.input :meta, as: :string%>
    <div class="form-actions">
        <%= f.button :submit, :class => 'btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    genomes_path, :class => 'btn' %>
    </div>
<% end %>

app/views/genomes/index.html.erb
<%- model_class = Genome -%>
<div class="page-header">
    <h1><%= t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<% if user_signed_in? %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
                new_genome_path,
                :class => 'btn btn-primary' %>
    <!--<hr>-->
<% end %>

<% unless @genomes.empty? %>
    <table class="table table-striped">
        <thead>
        <tr>
            <th><%= model_class.human_attribute_name(:organism) %></th>
            <th><%= model_class.human_attribute_name(:build_version) %></th>
            <th><%= model_class.human_attribute_name(:meta) %></th>
            <th><%= model_class.human_attribute_name(:created_at) %></th>
        </tr>
        </thead>
        <tbody>
        <% @genomes.each do |genome| %>
            <tr>
                <td><%= genome.organism %></td>
                <td><%= link_to genome.build_version, genome_path(genome) %></td>
                <td><%= genome.meta %></td>
                <td><%= l genome.created_at.to_date, format: :gee_fu %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
<% end %>

app/views/genomes/new.html.erb
<%- model_class = Genome -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/genomes/show.html.erb
<%- model_class = Genome -%>
<div class="page-header">
    <h1><%= t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">

<dt><strong><%= model_class.human_attribute_name(:organism) %>:</strong></dt>
    <dd><%= @genome.organism %></dd>
    <dt><strong><%= model_class.human_attribute_name(:build_version) %>:</strong></dt>
    <dd><%= @genome.build_version %></dd>
    <dt><strong><%= model_class.human_attribute_name(:meta) %>:</strong></dt>
    <dd><%= @genome.meta %></dd>
    <dt><strong><%= model_class.human_attribute_name(:created_at) %>:</strong></dt>
    <dd><%= l @genome.created_at.to_date, format: :gee_fu %></dd>
</dl>

<hr>
<h3>Experiments attached to this genome</h3>

<% unless @experiments.empty? %>

    <table class="table table-striped">
        <thead>
        <tr>
            <th><%= model_class.human_attribute_name(:name) %></th>
            <th><%= model_class.human_attribute_name(:description) %></th>
            <th><%= model_class.human_attribute_name(:created_at) %></th>
            <th>Features associated</th>
        </tr>
        </thead>
        <tbody>
        <% @experiments.each do |experiment| %>
            <tr>
                <td><%= link_to experiment.name, experiment_path(experiment) %></td>
                <td><%= experiment.description %></td>
                <td><%= l experiment.created_at.to_date, format: :gee_fu %></td>
                <td><%= experiment.features.count %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
<% else %>
    <p>None yet, Why not add one <a href="<%= experiments_path %>">HERE</a></p>
<% end %>

<div class="form-actions">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                genomes_path, :class => 'btn' %>
    <%#= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_genome_path(@genome), :class => 'btn' %>
              <a href="/wiki/<%= @genome.organism.local_name.downcase %>/<%= @genome.build_version.downcase %>" class="btn">Add/Edit Wiki page</a>
</div>