config/routes.rb
GeeFu::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  root :to => "pages#index"

  #get "/browse", :to => "experiments#index"
  get "/signed_up", :to => "pages#signed_up", :as => :signed_up
  get 'begin' => 'pages#index'

  authenticate :user do
    #resources :organisms
    #resources :genomes
    #resources :experiments
    #resources :features
    resources :tools
    resources :admin
  end

  resources :organisms
  resources :genomes
  resources :experiments
  resources :features

  scope "features" do
    get "/getgroup/:id", to: "features#getIdFromGroup"
  end

  scope "/features/search" do
    post "/id", to: "features#search_by_id", as: :feature_search_by_id
    post "/attribute", to: "features#search_by_attribute", as: :feature_search_by_attribute
    post "/summary", to: "features#summary", as: :feature_search_by_range
    get "/genome/typeahead", to: "features#genome_typeahead"
    get "/experiment/typeahead", to: "features#experiment_typeahead"
    post "/build", to: "features#display_all_by_build", as: :feature_display_all_by_build
  end

  scope "/tools" do
    post "/sequence", to: "tools#genomic_sequence", as: :tools_genomic_sequence
  end



  scope "/genomes" do
    get "/reference_list", to: "genomes#reference_list"
  end

  scope "/experiments" do
    get "/reference_list", to: "experiments#reference_list"
    get "/:id/:segment", to: "experiments#show"
  end

  scope "/features/dalliance" do
    get "/part/:exid/:part", to: "features#dalliance_part",:constraints => { :part => /.*/ }
    get "/:exid/:part", to: "features#dalliance_get",:constraints => { :part => /.*/ }
    get "/:exid/:part/:featutype/", to: "features#dalliance_get",:constraints => { :part => /.*/ }
  end

  scope "/genomes/dalliance/" do
    get "/:exid/:part/sequence", to: "features#dalliance_genome"
    get ":experiment/:sequence/entry_points", to: "features#dalliance_entry_points"
  end

  scope "/users" do
    get "/admin", to: "admin#index"
  end

  scope "/badges" do
    get "/badge/:badge", to: "Pages#getbadge"
    # get "/card/:email/:badge", to: "Pages#getcard"
  end

match "/badges/card/:email/:badge" => "Pages#getcard",
    :constraints => { :email => /.+@.+\..*/ }

  scope "/genomes/annoj" do
    get "/:id", to: "genomes#annoj"
  end

  match '/admin/:id', :to => 'admin#show', :as => :user

  mount SequenceServer::App, :at => "sequenceserver"

  scope "/sequenceserver" do
    get "/get_sequence", to: "experiments#findfromss"
  end

  # match "/webapollo" => redirect("http://geefu.oadb.tsl.ac.uk:8080/WebApollo/"), :as => :webapollo
  # match "/webapollo2" => redirect("http://geefu.oadb.tsl.ac.uk:8080/WebApollo2/"), :as => :webapollo2


require 'gollum/frontend/app'

  Precious::App.set(:gollum_path, Rails.root.join('wiki').to_s)
  Precious::App.set(:default_markup, :markdown) # set your favorite markup language
  Precious::App.set(:wiki_options, {:universal_toc => false})
  mount Precious::App, at: 'wiki'


# TODO review these for security
  resources :references
  match 'features/objects' => 'features#objects'
  match 'features/depth' => 'features#depth'
  match 'tools/genomic_sequence' => 'tools#genomic_sequence'
  match 'tools/export' => 'tools#export'
  match '/:controller(/:action(/:id))'
end

app/views/layouts/_navbar.html.erb
<div class="navwrapper">
    <div class="navbar navbar-inverse">
        <div class="navbar-inner">
            <ul id="nav_menu" class="nav">

                <li><a href="/">Home</a></li>
                <% if user_signed_in? && current_user.admin? %>
                    <li><a href="<%= organisms_path %>">Organisms</a></li>
                <% end %>
                <% if has_organisms? %>
                    <li><a href="<%= genomes_path %>">Genome Builds</a></li>
                    <li><a href="<%= experiments_path %>">Annotation Experiments</a></li>
                    <li><a href="<%= features_path %>">Features</a></li>
                    <li><a href="#">Tools</a>

                        <ul>
                            <li>
                                <a href="/sequenceserver" target="_blank">SequenceServer</a>
                            </li>
                            <!-- <li>
                                    <li>
                                      <a href="/browse" target="_blank">Gee Fu Browse</a>
                                  </li>
                            </li> -->
                            <li>
                            <li>
                                <a href="/webapollo" target="_blank">WebApollo - Chalara</a>
                            </li>
                            <li>
                                <a href="/webapollo2" target="_blank">WebApollo - Ash</a>
                            </li>
                            <li>
                                <a href="/wiki" target="_blank">Wiki</a>
                            </li>

                    </li>
                    </ul>
                    </li>


                <% end %>
            </ul>
            <ul id="nav_menu" class="nav pull-right">
                <% if user_signed_in? %>
                    <li>
                        <a href="#">
                            <i class="icon-user icon-white"></i>
                            Signed In
                        </a>
                        <ul>
                            <% if current_user.admin? %>
                                <li>
                                    <a href=/users/admin><i class="icon-wrench icon-white"></i> Admin</a>
                                </li>
                            <% end %>
                            <li>
                                <a href=<%= edit_user_registration_path %>><i class="icon-wrench icon-white"></i> My
                                    Account</a>
                            </li>
                            <li>
                                <a href=<%= destroy_user_session_path %>>Sign Out</a>
                            </li>
                        </ul>
                    </li>
                <% else %>
                    <li>
                        <%= link_to "Sign In", new_user_session_path, { :class=>"bold" } %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= @page_title or "OpenAshDieBack - GeeFu" %></title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <%unless params[:badge].nil?%>
        <script>console.log("loading cheves");</script>
        <script src="/Credit/src/frontend/cheeves.js"></script>
        <link href="/Credit/src/frontend/cheeves.css" media="all" rel="stylesheet" type="text/css" />
    <%end%>
</head>
<body>

<div id="page" class="container">
    <%= bootstrap_flash %>
    <%= render partial: "layouts/navbar" %>
    <div class="well">
        <%= yield %>
    </div>
</div>

<script>

    <%unless params[:badge].nil?%>
        <% if user_signed_in? %>
            console.log("running cheves");

            <% url = "http://127.0.0.1:3000" %>
            <% email = current_user.email %>
            <% badgep = params[:badge] %>

            card = <%= Badge.getCard(url, email, badgep) %>
            badge = <%= Badge.getBadge(url, badgep) %>
            cheeves.manualUpdate(card, badge);
        <% end %>
    <% end %>

</script>

<script>

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-36299627-3', 'tsl.ac.uk');
  ga('send', 'pageview');

</script>

<script src="/js/tooltips.js"></script>
</body>
</html>